version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: lendbooks
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    environment:
      - DATABASE_URL=postgresql://pguser:pgpass@db:5432/lendbooks
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db-data: